spring:
  application:
    name: server_app
#  ssl:
#    bundle:
#      pem:
#        mybundle:
#          keystore:
#            certificate: "classpath:server_.pem"
#            private-key: "classpath:server-key_.pem"
#          truststore:
#            certificate: "classpath:clientcert.crt"
server:
  port: 8086
  ssl:
    enabled: true
#    certificate: "classpath:server.pem"
#    certificate-private-key: "classpath:server-key.pem"
    client-auth: need
#    bundle: mybundle


    key-store: "classpath:keystore-server.p12"
#    key-store: "classpath:keystore-not-wanted-server.p12"
    key-store-password: keystorePass
    key-store-type: PKCS12

#    trust-store: "classpath:truststore.p12"
#    trust-store-password: truststorePass
#    trust-store-type: PKCS12